version: "3"

services:
  strapi:
    # image: strapi/strapi
    build:
      context: .
      args:
        BASE_VERSION: 14-alpine
        STRAPI_VERSION: 4.1.3
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    # environment:
    #   HOST: ${HOST}
    #   PORT: ${PORT}
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  postgres:
    container_name: postgres:13-alpine
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./db:/var/lib/postgresql/data
