name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: build & push to DockerHub
      with:
        image: dfang/strapi
        # tags: ${{ github.sha }}, ${{ steps.docker_meta.outputs.tags }}, latest
        tags: latest, ${{ github.sha }}
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        buildArgs: 'BASE_VERSION=14-alpine,STRAPI_VERSION=4.1.3'

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: build & push to ghcr.io
      with:
        image: dfang/strapi
        tags: latest, ${{ github.sha }}
        registry: ghcr.io
        username: dfang
        password: ${{ secrets.GHCR_TOKEN }}
        buildArgs: 'BASE_VERSION=14-alpine,STRAPI_VERSION=4.1.3'
